<?php
//-> b_data_thief.module

/**
 * Implements hook_menu().
 */
function b_data_thief_menu() {
  $items = array();

  $items['useful-telephones'] = array(
    'title' => t('Нужные телефоны'),
    'page callback' => 'b_data_thief_useful_telephones_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function b_data_thief_useful_telephones_page() {
  $dom = new DOMDocument();
  $dom->loadHTMLFile('http://borovoe.kz/index.php?option=com_content&view=article&id=89&Itemid=65');
  $xpath = new DOMXPath($dom);

  $rows = array();

  foreach ($xpath->query('//table[@class="MsoNormalTable"]') as $table) {
    foreach ($table->getElementsByTagName('tr') as $tr) {
      $row = array();
      foreach ($tr->getElementsByTagName('td') as $td) {
        $row[] = trim($td->nodeValue);
      }

      switch (count($row)) {
        case 1:
          $rows[] = array(array('data' => reset($row), 'colspan' => 3));
          break;
        case 4:
          unset($row[0]);
          $rows[] = $row;
          break;
      }

    }
  }
  // Delete empty rows.
  array_filter($rows);

  return theme('table', array('rows' => $rows));
}
